### PR TITLE
Option doctring formatting too inflexible - chg to support broader range of docstrings

### PR DESCRIPTION
**Pull request by mobileink**
The current docstring format - "Set <opt> to <docstr>" -  places too tight a constraint on docstrings, because it forces them to function as objects of a proposition.  Changing to "<opt> sets <docstr>" allows the developer to tack on explanatory text, e.g. "FOO sets bar.  Default is 0.  Setting to neg number means x."

### CODE REVIEW

**Comment by mobileink** [comment]
Make that "object of a preposition", not "proposition".

**Comment by micha** [comment]
@mobileink Awesome, looks great! If it's not too much trouble could you please rebase and make the PR against the 2.6.0-SNAPSHOT branch? If not I can do it later, no worries.

**Comment by mobileink** [comment]
On Wed, Feb 17, 2016 at 10:10 AM, Micha Niskin <notifications@github.com>
wrote:

> @mobileink <https://github.com/mobileink> Awesome, looks great! If it's
> not too much trouble could you please rebase and make the PR against the
> 2.6.0-SNAPSHOT branch? If not I can do it later, no worries.
>
If I can figure out how, I will. ;)

**Comment by mobileink** [comment]
Tried to follow https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request and something happened but I don't know what.  I'll try to find some time this weekend to do this.

**Comment by micha** [comment]
@mobileink it's cool i can do it when i merge all the outstanding PRs and stuff this weekend, no worries

**Pull request merged**
