### PR TITLE
Adding keybase support #388

### PR DESCRIPTION
**Pull request by instilled**
This is the minimal change required to make signing through keybase work.

### CODE REVIEW

**Comment by Deraen** [comment]
I think we should just merge this now and release this in a patch release. We can split the push task in 2.6 release.

**Comment by Deraen** [comment]
@instilled I've been experimenting with Keybase myself and in my set up I have gpg private key locally available using `gpg` so there is no need for me to use `keybase` to sign releases. Is there a set up where private key is not available to `gpg`?

**Comment by arichiardi** [comment]
@Deraen I think `keybase` might be a gpg replacement, meaning that it creates and manages the private keys for you, overriding `gpg`. I am guessing this because when I did my `keybase login` I was asked either to use `gpg` commands (`keybase` effectively wrapping `gpg`) or import my private key in `keybase` (full control in keybase). But of course it would be better to ask around if someone is using a vanilla `keybase` with no `gpg`...

**Comment by instilled** [comment]
@Deraen No, not really. It will probably take quite a while until keybase support signing without shelling out to GPG. This will require importing keys into the local GPG registry anyways. My motivation for using keybase is the easy setup and the command line interface that feels more natural to me. Also it will ask for the key's pass with copy&paste support if GPGTools are available (I manage my passwords in vault) as somehow with the native GPG I fail to paste it in the prompt. Otherwise than that there's no other benefit in using keybase instead of native GPG.

**Pull request closed without merging**
