### PR TITLE
Adding transfer-listener on aether/deploy

### PR DESCRIPTION
**Pull request by instilled**
When I deploy an artefact with the `push` task I would like to see progress logged to the console. Aether provides a `transfer-listener` for that. One was used in boot for resolving dependencies, see [resolve-dependencies*][rd].
For the `deploy` task this is easily solved by also registering a `transfer-listener` in [deploy][dp]. This PR adds `:transfer-listener` to `:stdout`. 

Open question: Is `:stdout` really the way you guys want to log [to the console] or shall it defer logging to a custom transfer listener as with [resolve-dependencies*][rd]?

[rd]: https://github.com/boot-clj/boot/blob/master/boot/aether/src/boot/aether.clj#L77
[dp]: https://github.com/instilled/boot/blob/deploy-logging/boot/aether/src/boot/aether.clj#L279

### CODE REVIEW

**Comment by alandipert** [comment]
Thanks!  I think it's probably best to go through util/info for this instead of stdout directly, the same way resolve-dependencies* does.

**Comment by Deraen** [comment]
This PR seems to also include keybase change which is not directly related to described changes.

**Comment by instilled** [comment]
@Deraen Sneaky keybase support commit that! Wasn't intended. Thanks for spotting.

**Comment by instilled** [comment]
@alandipert I've extended the `transfer-logging` to convey more information for the items being downloaded/uploaded. It's now logging everything that goes over the wire (pom, jar, war, etc).

**Comment by micha** [comment]
:+1: looking good! I deconflict and merge!

**Pull request merged**
