### PR TITLE
allow exclusion of specific directories from being watched

### PR DESCRIPTION
**Pull request by martinklepsch**
useful for node_modules and similar stuff

### CODE REVIEW

**Comment by martinklepsch** [comment]
@micha re your comment on #248

That would be less predictable and I assume the implementation would be more complex.
- We would need to traverse the tree and count files
- Then decide where we cut it off. Don't see a good decision criteria for this yet.

**Comment by micha** [comment]
We already are traversing the tree when we add the watchers. The way the fsevent stuff works you need to add a watcher to each directory---it needs a separate one for each directory. Like if you have a directory with subdirectories you need to add a watcher to each of the subdirectories and to each of their subdirectories etc. This is already in place, so we could do it there, couldn't we?

**Comment by micha** [comment]
Also boot relies on the file watchers to function correctly if you want those files to be in the fileset. So for something like node_modules i think you'd want a task that can just sync them to the target without ingesting them into the fileset. This will be much easier if we eliminated automatic target syncing and made it a separate task, as we discussed on slack.

**Comment by martinklepsch** [comment]
> Also boot relies on the file watchers to function correctly if you want those files to be in the fileset. 
The files in excluded dirs were still present in the fileset. I was also somewhat surprised tbh.

> So for something like node_modules i think you'd want a task that can just sync them to the target without ingesting them into the fileset.
Could I also add them to the classpath in a "static" way?

---
The traversing is there but essentially we would need another full traversal to create a tree of directories and filecounts right? Then we would still need to come up with some potentially arbitrary measures to decide whether to cut of a subtree from watching.

**Comment by martinklepsch** [comment]
> So for something like node_modules i think you'd want a task that can just sync them to the target without ingesting them into the fileset.

You might also want them on the classpath — are there means to put stuff on the classpath without it going through the fileset? Maybe the solution is a task that packages `node_modules` as a jar? 

Then we can also just forget about all of this stuff.

**Pull request closed without merging**
